codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "60...100"
  status:
    project:
      default:
        target: 60%
        threshold: 2%
    patch:
      default:
        target: 60%

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false

ignore:
  - "glue/target/**"
  - "glue/cli/tests/**"
  - "glue/*/src/main.rs"
  - "glue/wasm/**"
