// ------------------------------------
// Generated by Glue on 2026-02-07
// Source: ../../assets/config_schema.glue
// ------------------------------------

use std::collections::HashMap;

#[cfg(all(feature = "tsify", target_arch = "wasm32"))]
use wasm_bindgen::prelude::*;

#[cfg_attr(all(feature = "tsify", target_arch = "wasm32"), derive(tsify::Tsify))]
#[cfg_attr(all(feature = "tsify", target_arch = "wasm32"), tsify(into_wasm_abi, from_wasm_abi))]
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, Default)]
pub struct GlueConfigSchema {
    /// Configuration for code generation (`glue gen [...]`)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub generation: Option<GlueConfigSchemaGeneration>,
}

/// The Python modeling library
#[cfg_attr(all(feature = "tsify", target_arch = "wasm32"), derive(tsify::Tsify))]
#[cfg_attr(all(feature = "tsify", target_arch = "wasm32"), tsify(into_wasm_abi, from_wasm_abi))]
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
pub enum GlueConfigSchemaGenerationPythonDataModelLibrary {
    /// Pydantic (v2) BaseModel classes with Field() annotations
    #[serde(rename = "pydantic")]
    Pydantic,
    /// Standard library dataclasses
    #[serde(rename = "dataclasses")]
    Dataclasses,
    /// msgspec Struct classes
    #[serde(rename = "msgspec")]
    Msgspec,
}

#[cfg_attr(all(feature = "tsify", target_arch = "wasm32"), derive(tsify::Tsify))]
#[cfg_attr(all(feature = "tsify", target_arch = "wasm32"), tsify(into_wasm_abi, from_wasm_abi))]
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, Default)]
pub struct GlueConfigSchemaGenerationPython {
    /// The Python modeling library to use. Defaults to "pydantic".
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data_model_library: Option<GlueConfigSchemaGenerationPythonDataModelLibrary>,
    /// For pydantic: the full import path for the base model class. Defaults to `pydantic.BaseModel`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub base_model: Option<String>,
}

/// Mode for generating the watermark comment at the top of generated files
#[cfg_attr(all(feature = "tsify", target_arch = "wasm32"), derive(tsify::Tsify))]
#[cfg_attr(all(feature = "tsify", target_arch = "wasm32"), tsify(into_wasm_abi, from_wasm_abi))]
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
pub enum GlueConfigSchemaGenerationWatermark {
    /// Includes full details including generation timestamp, Glue version, source file, etc.
    #[serde(rename = "full")]
    Full,
    /// Includes minimal details such as the the timestamp and source file
    #[serde(rename = "short")]
    Short,
    /// No watermark comment is included
    #[serde(rename = "none")]
    None,
}

#[cfg_attr(all(feature = "tsify", target_arch = "wasm32"), derive(tsify::Tsify))]
#[cfg_attr(all(feature = "tsify", target_arch = "wasm32"), tsify(into_wasm_abi, from_wasm_abi))]
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, Default)]
pub struct GlueConfigSchemaGeneration {
    /// Mode for the watermark at the top of the generated files. Defaults to "short" if not specified.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub watermark: Option<GlueConfigSchemaGenerationWatermark>,
    /// Configurations for Python code generation (`glue gen python [...]`)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub python: Option<GlueConfigSchemaGenerationPython>,
}
