// ------------------------------------
// Generated by Glue on 2025-11-02
// Source: ../../assets/config_schema.glue
// ------------------------------------

use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, Default)]
pub struct GlueConfigSchema {
    /// Configuration for code generation (`glue gen [...]`)
    pub generation: GlueConfigSchemaGeneration,
}

fn default_glue_config_schema_generation_watermark() -> GlueConfigSchemaGenerationWatermark {
    GlueConfigSchemaGenerationWatermark::Short
}
fn default_glue_config_schema_generation_python_pydantic_base_model() -> String {
    "pydantic.BaseModel".to_string()
}
#[derive(Serialize, Deserialize, Debug, Clone, Default)]
pub struct GlueConfigSchemaGenerationPythonPydantic {
    #[serde(default = "default_glue_config_schema_generation_python_pydantic_base_model")]
    /// The full import path for the base model class to inherit from (e.g., `pydantic.BaseModel` or `my.module.CustomBaseModel`)
    pub base_model: String,
}

/// Mode for generating the watermark comment at the top of generated files
#[derive(Serialize, Deserialize, Debug, Clone)]
pub enum GlueConfigSchemaGenerationWatermark {
    /// Includes full details including generation timestamp, Glue version, source file, etc.
    #[serde(rename = "full")]
    Full,
    /// Includes minimal details such as the the timestamp and source file
    #[serde(rename = "short")]
    Short,
    /// No watermark comment is included
    #[serde(rename = "none")]
    None,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct GlueConfigSchemaGeneration {
    #[serde(default = "default_glue_config_schema_generation_watermark")]
    /// Mode for the watermark at the top of the generated files
    pub watermark: GlueConfigSchemaGenerationWatermark,
    /// Configurations for Python code generation using Pydantic (`glue gen py-pydantic [...]`)
    pub python_pydantic: GlueConfigSchemaGenerationPythonPydantic,
}

impl Default for GlueConfigSchemaGeneration {
    fn default() -> Self {
        Self {
            watermark: default_glue_config_schema_generation_watermark(),
            python_pydantic: Default::default(),
        }
    }
}
