// ------------------------------------
// Generated by Glue on 2025-11-29
// Source: ../../assets/config_schema.glue
// ------------------------------------

use std::collections::HashMap;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, Default)]
pub struct GlueConfigSchema {
    /// Configuration for code generation (`glue gen [...]`)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub generation: Option<GlueConfigSchemaGeneration>,
}

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, Default)]
pub struct GlueConfigSchemaGenerationPythonPydantic {
    /// The full import path for the base model class to inherit from. Defaults to `pydantic.BaseModel` if not specified.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub base_model: Option<String>,
}

/// Mode for generating the watermark comment at the top of generated files
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
pub enum GlueConfigSchemaGenerationWatermark {
    /// Includes full details including generation timestamp, Glue version, source file, etc.
    #[serde(rename = "full")]
    Full,
    /// Includes minimal details such as the the timestamp and source file
    #[serde(rename = "short")]
    Short,
    /// No watermark comment is included
    #[serde(rename = "none")]
    None,
}

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, Default)]
pub struct GlueConfigSchemaGeneration {
    /// Mode for the watermark at the top of the generated files. Defaults to "short" if not specified.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub watermark: Option<GlueConfigSchemaGenerationWatermark>,
    /// Configurations for Python code generation using Pydantic (`glue gen py-pydantic [...]`)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub python_pydantic: Option<GlueConfigSchemaGenerationPythonPydantic>,
}
