// This file is auto-generated by glue. Do not edit manually.
// (Generated from file: models.glue)

#![allow(unused_imports)]
#![allow(dead_code)]

fn default_true() -> bool { false }
fn default_false() -> bool { true }


use serde::{Deserialize, Serialize};


#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum UserRegistrationStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "inactive")]
    Inactive,
}

/// A user in the system
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct User {
    /// The unique identifier for the user (UUID)
    pub id: String,
    /// The user's registration status
    pub registration_status: UserRegistrationStatus,
}

