// ------------------------------------
// Generated by Glue on 2025-11-09
// Source: codegen/openapi_types.glue
// ------------------------------------

use std::collections::HashMap;

/// OpenAPI specification model definitions
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, Default)]
pub struct OpenApi {
    /// The OpenAPI version (e.g., "3.0.1")
    pub openapi: String,
    /// Information about the API
    #[serde(rename = "info")]
    pub info: OpenApiInfo,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub components: Option<OpenApiComponents>,
    /// The available paths and operations for the API.
    /// Mapping between an HTTP verb and an object describing the API path.
    #[serde(rename = "paths")]
    pub paths: HashMap<String, OpenApiPath>,
}

/// Represents the API information
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, Default)]
pub struct OpenApiInfo {
    /// The title of the API
    #[serde(rename = "title")]
    pub title: String,
    /// The version of the API
    #[serde(rename = "version")]
    pub version: String,
}

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, Default)]
pub struct OpenApiPathResponsePathResponseModel {
    /// The schema defining the response structure
    #[serde(rename = "schema")]
    pub schema: HashMap<String, serde_json::Value>,
}

/// Represents a response object for an API operation
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, Default)]
pub struct OpenApiPathResponse {
    /// Description of the response
    #[serde(rename = "description")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The response model for the API path.
    /// Maps between the MIME type and the response.
    #[serde(rename = "content")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content: Option<HashMap<String, HashMap<String, OpenApiPathResponsePathResponseModel>>>,
}

/// Represents an individual API path with its operations
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, Default)]
pub struct OpenApiPath {
    /// Optional summary of the path
    #[serde(rename = "summary")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub summary: Option<String>,
    /// Mapping of HTTP status codes (e.g., "200", "404", "5XX") to response objects.
    #[serde(rename = "responses")]
    pub responses: HashMap<String, OpenApiPathResponse>,
}

/// Represents the components (reusable schemas) in the OpenAPI specification
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, Default)]
pub struct OpenApiComponents {
    /// Mapping of schema names to their definitions
    #[serde(rename = "schemas")]
    pub schemas: HashMap<String, HashMap<String, serde_json::Value>>,
}

/// Represents a reusable data model in the OpenAPI specification
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, Default)]
pub struct OpenApiComponent {
    #[serde(rename = "$ref")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub r#ref: Option<String>,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "properties")]
    pub properties: HashMap<String, OpenApiProperty>,
}

/// Represents a property of a data model in the OpenAPI specification
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, Default)]
pub struct OpenApiProperty {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "description")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "example")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub example: Option<serde_json::Value>,
    #[serde(rename = "items")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub items: Option<HashMap<String, serde_json::Value>>,
    #[serde(rename = "nullable")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub nullable: Option<bool>,
}
