use crate::codegen::GlueConfigSchemaGenerationWatermark;

/// Generate watermark comments based on the specified mode.
/// The lines themselves are generated, they should be commented appropriately by the caller.
pub fn generate_watermark(source_file: &str, mode: &GlueConfigSchemaGenerationWatermark) -> Vec<String> {
    match mode {
        GlueConfigSchemaGenerationWatermark::None => vec![],
        GlueConfigSchemaGenerationWatermark::Short => vec![
            "This file is auto-generated by glue. Do not edit manually.".to_string(),
            format!("(Generated from file: {source_file})"),
        ],
        GlueConfigSchemaGenerationWatermark::Full => {
            let today = chrono::Utc::now().format("%Y-%m-%d").to_string();
            vec![
                "This file is auto-generated by glue. Do not edit manually.".to_string(),
                format!("(Generated from file {source_file} on {today})"),
            ]
        }
    }
}
