// ------------------------------------
// Generated by Glue on 2026-02-09
// Source: config_schema.glue
// ------------------------------------

export type GlueConfigSchema = {
  /**
   * Global defaults applied to all generation entries
   */
  global?: GlueConfigSchemaGlobal;
  /**
   * Per-generation configuration entries
   */
  gen?: GlueConfigSchemaGenConfig[];
};

export type GlueConfigSchemaGlobal = {
  /**
   * Base directory for generated output (relative to the config file if not absolute)
   */
  output_base_dir?: string;
  /**
   * Default code generation configuration
   */
  config?: GlueConfigSchemaGeneration;
};

export type GlueConfigSchemaGenConfig = {
  /**
   * Glob selector for input files
   */
  files: string;
  /**
   * Output path template (supports {file_name} and {file_ext})
   */
  output?: string;
  /**
   * Per-generation configuration overrides
   */
  config_overrides?: GlueConfigSchemaGeneration;
};

export type GlueConfigSchemaGeneration = {
  /**
   * Whether to emit lint suppression comments in generated files. Defaults to true.
   */
  lint_suppressions?: boolean;
  /**
   * Configurations for TypeScript code generation (`glue gen typescript [...]`)
   */
  typescript?: GlueConfigSchemaGenerationTypeScript;
  /**
   * Mode for the watermark at the top of the generated files. Defaults to "short" if not specified.
   */
  watermark?: GlueConfigSchemaGenerationWatermark;
  /**
   * Configurations for Python code generation (`glue gen python [...]`)
   */
  python?: GlueConfigSchemaGenerationPython;
  /**
   * Configurations for Rust code generation (`glue gen rust [...]`)
   */
  rust?: GlueConfigSchemaGenerationRust;
};

export type GlueConfigSchemaGenerationTypeScript = {
  /**
   * Whether to emit Zod schemas and use z.infer for types. Defaults to false.
   */
  zod?: boolean;
};

export type GlueConfigSchemaGenerationPython = {
  /**
   * The Python modeling library to use. Defaults to "pydantic".
   */
  data_model_library?: GlueConfigSchemaGenerationPythonDataModelLibrary;
  /**
   * For pydantic: the full import path for the base model class. Defaults to `pydantic.BaseModel`.
   */
  base_model?: string;
};

/**
 * The Python modeling library
 */
export type GlueConfigSchemaGenerationPythonDataModelLibrary = "pydantic" | "dataclasses" | "attrs" | "msgspec";

export type GlueConfigSchemaGenerationRust = {
  /**
   * Include serde_yaml support in generated output
   */
  include_yaml?: boolean;
};

/**
 * Mode for generating the watermark comment at the top of generated files
 */
export type GlueConfigSchemaGenerationWatermark = "full" | "short" | "none";

