"""
This file is auto-generated by glue. Do not edit manually.
(Generated from file: ./models.glue)
"""

from custom_models import CustomBaseModel
from pydantic import Field, BaseModel
from enum import StrEnum
from typing import Annotated, List, Optional

class User(CustomBaseModel):
    class RegistrationStatus(StrEnum):
        PENDING = "pending"
        ACTIVE = "active"
        INACTIVE = "inactive"
    

    id: Annotated[str, Field()]
    """The unique identifier for the user (UUID)"""

    registration_status: Annotated[RegistrationStatus, Field(alias="registrationStatus")]
    """The user's registration status"""

